name: Android Build For Me

on:
  workflow_dispatch: # 允许你在 Actions 页面手动点击按钮运行打包

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 核心修改：改为 assembleDebug 打测试包，并删除了你需要不到的私密 Token
      - name: Build apk file with Gradle
        run: ./gradlew assembleDebug
        env:
          UMENG_CHANNEL: GithubRelease

      # 核心修改：不再尝试发布 Release，而是打包成普通的压缩包供你下载
      - name: Upload apk file
        uses: actions/upload-artifact@v4
        with:
          name: Chaoxing-App-Debug
          path: app/build/outputs/apk/debug/*.apk